version: "3.9"
services:
  web:
    container_name: "web"
    build: CountryHolidays/.
    # command: /bin/bash dotnet sql-cache create "Data Source=localhost;Initial Catalog=DistCache;Persist Security Info=True;User ID=sa;Password=AdminPassword1!" dbo CacheStore
    environment:
      ASPNETCORE_ENVIRONMENT: "Docker"
      ASPNETCORE_URLS: "https://+:443;http://+:80"
      ASPNETCORE_Kestrel__Certificates__Default__Password: "AdminPassword1!"
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/https/holidaysapp.pfx"
    volumes:
      - ~/.aspnet/https:/https:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - sqlserver
  sqlserver:
    hostname: sqlserver
    container_name: sqlserver
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      MSSQL_SA_PASSWORD: "AdminPassword1!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - ~/apps/mssql/data:/var/lib/mssqlql/data